const mongoose = require('mongoose');

const qpFileDataSchema = new mongoose.Schema(
    {
        file_id: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'UploadedFile',
            required: true,
            index: true,
        },
        file_name: String,
        file_url: String,
        row_number: Number,
        reported_date: { type: Date, index: true },
        ota: {
            type: String,
            enum: [null, 'Expedia', 'Booking', 'Agoda'],
            default: null,
            index: true,
        },

        // QP report fields
        mid: { type: String, index: true },
        dba: String,
        transaction_date_time_local: String,
        transaction_date_local: String,
        transaction_id: { type: String, index: true },
        payment_type: String,
        processor_id: String,
        type: String,
        account: String,
        account_expiration: String,
        order_id: String,
        order_description: String,
        time: String,
        amount: Number,
        status: String,
        response: String,
        response_text: String,
        avs_results: String,
        csc_results: String,
        auth_code: String,
        batch_id: String,
        first_name: String,
        last_name: String,
        company_name: String,
        address_one: String,
        address_two: String,
        city: String,
        state: String,
        zip_code: String,
        country: String,
        email: String,
        shipping_first_name: String,
        shipping_last_name: String,
        shipping_to_company_name: String,
        shipping_to_address_one: String,
        shipping_to_address_two: String,
        shipping_to_city: String,
        shipping_to_state: String,
        shipping_to_postal_code: String,
        shipping_to_country: String,
        shipping_email: String,
        phone_number: String,
        fax: String,
        user_name: String,
        entry_method: String,
        service_type: String,
        descriptor_dba: String,
        descriptor_phone_number: String,
        authentication_result: String,
    },
    { timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } }
);

module.exports = mongoose.model('QpFileData', qpFileDataSchema);